### ISSUE TITLE
vrouter dpdk mode support simple gateway now?

### ISSUE THREAD

**Issue by HehuaTang** [Juniper/contrail-vrouter#91]
I used  R3.0 branch and dpdk_2_1 branch to setup contrail environment successfully. When vrouter worked in DPDK mode, If I ENABLE simple gateway, The contrail-vrouter-dpdk process will crash in function dpdk_vhost_if_add() when add vgw vif in the vrouter. Backtrace is as follows.
The root casue is that pointer vif->vif_bridge is null.  
I want to know that  is this just a bug or contrail do not want to support simple gateway in the dpdk version. 

#0  0x0000000000767595 in dpdk_vhost_if_add ()
#1  0x0000000000767d99 in dpdk_if_add ()
#2  0x00000000007a89f5 in vhost_drv_add ()
#3  0x00000000007aa651 in vif_drv_add ()
#4  0x00000000007aace9 in vr_interface_add ()
#5  0x00000000007abdbc in vr_interface_req_process ()
#6  0x00000000007dded0 in sandesh_decode_one ()
#7  0x00000000007ddf5f in sandesh_decode ()
#8  0x00000000007be657 in sandesh_proto_decode ()
#9  0x00000000007affa9 in vr_message_request ()
#10 0x0000000000778df4 in dpdk_netlink_receive ()
#11 0x000000000077e87a in usock_read_done ()
#12 0x000000000077f6aa in vr_usocket_read ()
#13 0x000000000077fe7f in vr_usocket_io ()
#14 0x0000000000778917 in dpdk_lcore_netlink_loop ()
#15 0x0000000000778baf in vr_dpdk_lcore_launch ()
#16 0x000000000045d9c2 in eal_thread_loop ()
#17 0x00002ad521cdcdf5 in ?? ()
#18 0x0000000000000000 in ?? ()

**Comment by hnakil** [comment]
Simple gateway is not supported with DPDK yet. 

Regards
-Harshad

**Comment by HehuaTang** [comment]
Thanks Harshad.
